name: CNN - RAG
run-name: Question-Answer - ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}
on: 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    paths:
      - 'cnn-rag/**'

env:
  PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  PINECONE_INDEX_NAME: canopy--pinecone-multitenant-rag-demo
  PINECONE_NAMESPACE: wbd

jobs:
  Build-RunDataPipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: |
          cd cnn-rag
          poetry install
      - name: Run data pipeline - CNN scrape
        run: |
          cd cnn-rag 
          poetry run python data_pipeline.py scrape_cnn
      - name: Run data upsert
        run: |
          cd cnn-rag 
          poetry run python data_pipeline.py upsert